version: '3.3'

services:
  web:
    container_name: "mk-bot"
    image: mk-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - users-db:/mk-bot_bd
volumes:
  users-db:
    external: true # нужн создать volume в ручную командой sudo docker volume create --name users-db
